name: Build GH Pages

on:
  repository_dispatch:
    types: [documentation-update]
  workflow_dispatch: {}

env:
  DOCUMENTATION_SOURCE_REPO: btp-automated-documentation
  DOCUMENTATION_SOURCE_OWNER: btp-setup-automator
  DOCUMENTATION_SOURCE_PATH: docs
  DOCUMENTATION_TARGET_PATH: docs
jobs:
  fetch-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"
        with:
          ref: documentation
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Prepare collection of data from documentation repository"
        run: |
          cd ${{ github.workspace }}/.github/workflows/js
          npm ci
      - name: "Execute collection of data from documentation repository"
        run: |
          cd ${{ github.workspace }}/.github/workflows/js
          export DOCUMENTATION_READ_TOKEN=${{ secrets.DOCUMENTATION_READ_TOKEN }} 
          export DOCUMENTATION_SOURCE_PATH=${{ env.DOCUMENTATION_SOURCE_PATH }}  
          export DOCUMENTATION_TARGET_PATH=${{ github.workspace }}/${{ env.DOCUMENTATION_TARGET_PATH}}
          export DOCUMENTATION_SOURCE_OWNER=${{ env.DOCUMENTATION_SOURCE_OWNER }}
          export DOCUMENTATION_SOURCE_REPO=${{ env.DOCUMENTATION_SOURCE_REPO }}
          npm run fetch:docu
      - name: "Store changes in GH repository"
        run: |
          git add -A
          git config user.email "btpsabot@users.noreply.github.com"
          git config user.name "BTPSA Bot"
          git diff --quiet && git diff --staged --quiet || git commit -m "[btpsa-bot] $(date '+%Y-%m-%d %H:%M:%S'): fetched service documentation"
          git push origin documentation

  build-and-deploy-page:
    runs-on: ubuntu-latest
    needs: fetch-documentation
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3
        name: "Checkout repository"
        with:
          ref: documentation
      - name: "Fetch latest changes"
        run: |
          git pull
      - name: "Deploy docs to GH pages"
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
